### ISSUE TITLE
Airportltlwm

### ISSUE THREAD

**Issue by Kratos-82** [Gilberto-Mascena/Z390-DESIGNARE#1]
Hi, I wanted to let you know that Intel WiFi with this version of the KEXT doesn't work

**Comment by Kratos-82** [comment]
[Uploading AirportItlwm-SonomaBeta5-Preview05.kext.zip…]() no problem with this

**Comment by Gilberto-Mascena** [comment]
Dear Kratos-82, this EFI is from a studio client who needs macOS Big Sur. This way this EFI will not undergo changes that do not suit my client, I hope you understand!
If you are using another version of macOS, replace the kext(s) that meet your needs.
Cordially, Gilberto Mascena.
